/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'AuthStatus.component': typeof import('./src/components/AuthStatus.component.vue')['default']
    'CollectionPokemonCard.component': typeof import('./src/components/CollectionPokemonCard.component.vue')['default']
    'DeckCards.component': typeof import('./src/components/DeckCards.component.vue')['default']
    'DeckDetails.component': typeof import('./src/components/DeckDetails.component.vue')['default']
    'DeckHeader.component': typeof import('./src/components/DeckHeader.component.vue')['default']
    'DeckPokemonList.component': typeof import('./src/components/DeckPokemonList.component.vue')['default']
    'DeckTable.component': typeof import('./src/components/DeckTable.component.vue')['default']
    'DeleteConfirmation.component': typeof import('./src/components/DeleteConfirmation.component.vue')['default']
    'EmptyStates.component': typeof import('./src/components/EmptyStates.component.vue')['default']
    'HeaderMenu.component': typeof import('./src/components/HeaderMenu.component.vue')['default']
    'HeaderSection.component': typeof import('./src/components/HeaderSection.component.vue')['default']
    'LoginForm.component': typeof import('./src/components/LoginForm.component.vue')['default']
    'MiniPokemonCard.component': typeof import('./src/components/MiniPokemonCard.component.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescription: typeof import('naive-ui')['NDescription']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImg: typeof import('naive-ui')['NImg']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    'PokemonCard.component': typeof import('./src/components/PokemonCard.component.vue')['default']
    'PokemonCollection.component': typeof import('./src/components/PokemonCollection.component.vue')['default']
    'PokemonDetailsModal.component': typeof import('./src/components/PokemonDetailsModal.component.vue')['default']
    'RegisterForm.component': typeof import('./src/components/RegisterForm.component.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
